packages:
  - apps/**
  - packages/**

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - rolldown

overrides:
  "@babel/helper-module-imports": "7.27.1"
  "@rolldown/pluginutils": "nightly"
  "@vitejs/plugin-react": "$@vitejs/plugin-react"
  "@vitejs/plugin-vue": "$@vitejs/plugin-vue"
  "fs-extra": "8.1.0"
  "vite": "latest"
  "zod": "$zod"
  "@astrojs/vue>@vitejs/plugin-vue-jsx": "-"
  "@astrojs/vue>vite-plugin-vue-devtools": "-"
  "astro>sharp": "-"

shellEmulator: true