name: Web

on: workflow_dispatch

env:
  CI: true

jobs:
  deploy:
    name: Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'pnpm'
      
      - name: Install
        run: pnpm install
      
      - name: Build
        run: pnpm exec turbo build --filter=web